#!/usr/bin/env perl
#-*-perl-*-
#

=head1 NAME

opus-swap-align

=head1 USAGE

  opus-swap-align < input > output

=head1 OPTIONS

=head1 DESCRIPTION

Swap languages in XCES sentence alignment files.

=cut


use strict;

while (<>){
    s/fromDoc/toNewDoc/;
    s/toDoc/fromNewDoc/;
    s/NewDoc/Doc/g;
    s/(xtargets=[\"\'])([^\"\']*);([^\"\']*)([^\"\']*)/$1$3;$2$4/;
    s/(type=[\"\'])([^\"\']*)\-([^\"\']*)([^\"\']*)/$1$3\-$2$4/;
    print;
}
